### PR TITLE
Oh My ZSH Aliases

### PR DESCRIPTION
**Pull request by ahmadawais**
# Oh My ZSH Aliases
If you are an OH MY ZSH user, you can use following aliases to speed things up. Put these in your `.zshrc` file or your alias file as per your workflow.

```bash
#
# Git Reflow Aliases.
#

# Usage: grf start aa-feature
alias grf="git reflow $@"

# Usage: grfs aa-feature
alias grfs="git reflow start $@"

# Usage: grfr
alias grfr="git reflow review"

# Usage: grfd
alias grfd="git reflow deliver"

# Usage: grfrefresh
alias grfd="git reflow refresh"

# Usage: grfst
alias grfd="git reflow status"
```

### CODE REVIEW

**Comment by timraasveld** [comment]
Good idea. You don't even need Oh-My-ZSH to do this, plain Bash(or zsh for that matter) also supports aliases :-)

**Comment by ahmadawais** [comment]
@timraasveld Thanks for the + vote. I use OH My ZSH so, was not sure if these would work for other workflows. I think we can wait for @codenamev  to respond :)

**Comment by pboling** [comment]
I have similar aliases for bash, and will begin using these for git reflow.  Thanks!

**Comment by ahmadawais** [comment]
@pboling Glad you found them useful.

**Comment by codenamev** [comment]
I think I would rather see these as [git aliases](https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases).  We could then offer a setup subcommand `git reflow setup aliases` that could just add them to the user's config file automatically :smile:

**Comment by codenamev** [comment]
@ahmadawais closing this in favor of moving toward git-aliases (tracking this with #191).  If you'd like, please update the README with instructions on adding git aliases and I'll re-open this.

**Pull request closed without merging**
