### PR TITLE
[54] Setup special Reflow config file and include it in setup command

### LINKED ISSUE #54: Store OAuth token somewhere else?
I have my dotfiles in a public git repository. `~/.git/config` is one of those files. In the current way of storing the OAuth token, I can't add the config line to the gitignore. What is the best way to make sure I never commit this?

I'd be happy to add something that can store the token in a different file, and maybe then put the file location in the git config? Is this something you'd merge in?

### PR DESCRIPTION
**Pull request by codenamev**
* #54 - Create new ~/.gitconfig.reflow file and include it in global .gitconfig
* All git config settings now update and reference the new reflow specific config file

Fixes #54

### CODE REVIEW

**Comment by nhance** [comment]
I was going to suggest we don't do this to keep from littering repositories with unused files, but I think it makes a ton of sense if you are running `git reflow setup` from inside a git repository directory.

Should we include defaults in this file so people can easily config?

**Comment by codenamev** [comment]
This will create a Reflow specific git config file in the user's home
directory (I'll update the path lookup for that). I noticed this setup in
Thoughtbot's dot files and thought it was a good use case as well. Nothing
gets added to the project ;-) this is just a way for us to establish a
single file for the git config that houses everything reflow :-)

On Friday, March 11, 2016, Nicholas Hance <notifications@github.com> wrote:

> I was going to suggest we don't do this to keep from littering
> repositories with unused files, but I think it makes a ton of sense if you
> are running git reflow setup from inside a git repository directory.
>
> Should we include defaults in this file so people can easily config?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reenhanced/gitreflow/pull/150#issuecomment-195544394>.
>


-- 

Cheers,
Valentino

**Comment by nhance** [comment]
totally okay with that! I thought it was project specific, sorry

**Comment by nhance** [comment]
lgtm

**Pull request closed without merging**
