### PR TITLE
[issue: 162] Updating Rspecs: Use "Allow" instead of "Stub"

### PR DESCRIPTION
**Pull request by simonzhu24**
Using `Transpec` Gem to Update Rspecs:

[https://github.com/yujinakayama/transpec](url)

Thanks @pboling for suggesting such a great gem!

### CODE REVIEW

**Comment by codenamev** [comment]
Can you rebase off master please?  Looks like you branched off of the work for adding the Nx LGTM :wink:

**Comment by simonzhu24** [comment]
Yup, I was hoping you wouldn't notice, I just fixed it :wink:

**Comment by codenamev** [comment]
Still seeing the commits old commits there (https://github.com/reenhanced/gitreflow/pull/163/commits/4ccb0bbeb0afcc712799025f6e6db4cffa42f5f5 and https://github.com/reenhanced/gitreflow/pull/163/commits/8562d05400a4b7e8478eff1b7de0db59c106d0b2).  Try an interactive rebase and pull them off of there: `rebase -i origin/master` and just remove the top two commits listed.  Then you'll have to force-push this branch :cold_sweat:

**Comment by simonzhu24** [comment]
Yup

**Comment by codenamev** [comment]
This is great, LGTM!  Thanks again :smile:

**Comment by codenamev** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nzFhAUqt&#x2F;13-upgrade-rspec"> Upgrade RSpec</a>

**Pull request merged**
